name: Report Bug
description: Report a problem or unexpected behavior.
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, please [search](https://github.com/kimitrii/legion-website/issues) to ensure you are not reporting a duplicate problem. If you find an equivalent issue, consider contributing additional information if necessary.
  - type: textarea
    attributes:
      label: Description
      description: What kind of issue did you encounter? Please describe it clearly and include images if applicable.
      placeholder: |
        I encountered a problem on the ... page while trying to...
        The result was this:
        ![image](https://example.com/image)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce the issue
      description: What steps are required for someone else to reproduce this issue?
      placeholder: |
        1. As a logged-in user, navigate to the page...
        2. Click on...
        3. Perform...
        4. Return to ... and observe the error.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Browsers tested
      description: Which browsers did you notice this issue in?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Microsoft Edge
        - Safari
        - Other
  - type: textarea
    attributes:
      label: Possible Solution
      description: Have you thought of anything that might resolve this issue? If so, please share it below.
      placeholder: |
        Instead of ..., we could change ... to...
        Here is an example of how it might look:
        ![image](https://example.com/image)
