name: Deploy Cloudflare

on:
  push:
    branches:
      - main
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow --tags

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Run all tests
        run: pnpm run test

  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: ["test"]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Build
        run: pnpm run pages:build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy .vercel/output/static --project-name=legion-frontend
      